### ISSUE TITLE
裝備匯出匯入

### ISSUE THREAD

**Issue by hugkoala** [Landgris/ROCalculator#6]
感謝大大的計算機讓小弟少走了好多冤枉路，想詢問會有儲存裝備匯出匯入的功能嗎

**Comment by Landgris** [comment]
那部份好久之前寫的狗屎爛扣 要做的話要花很多時間看了QQ

Leo ***@***.***> 於 2024年2月25日 週日 下午1:42寫道：

**Comment by hugkoala** [comment]
了解 辛苦了!!
